Increase timeout for deploy step of deploy-sfdx-project to 2 hours
wtaxco/wtax-github-actions-workflows pull request #11
Opened 2024-05-28 11:27 UTC by YonniPa

2024-05-28 11:38 UTC, fransf-wtax requested changes

2024-05-28 11:38 UTC, fransf-wtax commented on .github/workflows/deploy-sfdx-project.yml
> +    timeout-minutes: 120
This would set the timeout for the GitHub Actions workflow. The timeout error (`Error (1): Metadata API request failed: The client has timed out.`), however, seems to be coming from the Salesforce CLI, so I'm not sure if setting a GitHub Actions workflow timeout will have any effect.
Also, per [the documentation](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes), the default job timeout is 360 minutes, so setting it to 120 minutes would *shorten* the timeout.

2024-05-28 11:55 UTC, fransf-wtax commented on .github/workflows/deploy-sfdx-project.yml
> +    timeout-minutes: 120
Oh, can you create a ticket for this, either in WDC or WSS, so that we can link the commits to it? Thanks :)

2024-05-28 11:59 UTC, YonniPa commented on .github/workflows/deploy-sfdx-project.yml
> +    timeout-minutes: 120
Created: https://wtax.atlassian.net/browse/WSS-49. Will make the suggested change and request to merge into the testing branch. Great catch!

2024-05-30 05:26 UTC, YonniPa commented
Closing this PR as we'd rather go with the implementation here: https://github.com/wtaxco/wtax-github-actions-workflows/pull/12 that can be merged into the `testing` branch.

2024-05-30 05:26 UTC, closed without merging